import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:new_m/pages/gpt.dart';
import 'package:new_m/pages/home.dart';
import 'package:new_m/pages/index.dart';
import 'package:new_m/pages/notification.dart';
import 'package:new_m/pages/profile_created.dart';
import 'package:new_m/pages/success.dart';
import 'package:new_m/pages/create_profile.dart';
import 'package:new_m/pages/test_ui.dart';
import 'package:new_m/pages/tree_welcome.dart';
import 'package:new_m/pages/welcome.dart';
import 'package:new_m/pages/login_email.dart';
import 'package:new_m/pages/splash.dart';
import 'package:new_m/pages/login_phone.dart';
import 'package:new_m/pages/register_email.dart';
import 'package:new_m/pages/reset_password.dart';
import 'package:new_m/pages/login_phone_code.dart';
void main() {
   SystemChrome.setSystemUIOverlayStyle(
    SystemUiOverlayStyle(
      statusBarColor: Colors.grey[100], // Change this color to the desired color
      statusBarIconBrightness: Brightness.light, // Change the icon color to light or dark
    ),
  );
  runApp(MaterialApp(
    initialRoute: '/index',
    routes: {
      '/': (context) => WelcomePage(),
      '/sign_in_option': (context) => MyHomePage(),
      '/register_email':(context) => RegisterEmail(),
      '/login_email':(context) => LoginEmail(),
      '/splash':(context) => SplashScreen(),
      '/login_phone':(context) => LoginPhone(),
      '/reset_password':(context) => ResetPassword(),
      '/login_phone_code':(context) => LoginPhoneCode(),
      '/success':(context) => Success(),
      '/create_profile':(context) => ProfilePage(),
      '/profile_created':(context) => ProfileCreated(),
      '/notification':(context) => Notifi(),
      '/welcome':(context) => Welcome(),
      '/index':(context) => Balance(),
      '/test':(context) => TestUi(),
    },
  ));
}
// import 'package:flutter/material.dart';

// void main() {
//   runApp(const FigmaToCodeApp());
// }

// // Generated by: https://www.figma.com/community/plugin/842128343887142055/
// class FigmaToCodeApp extends StatelessWidget {
//   const FigmaToCodeApp({super.key});

//   @override
//   Widget build(BuildContext context) {
//     return MaterialApp(
//       theme: ThemeData.dark().copyWith(
//         scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
//       ),
//       home: Scaffold(
//         body: ListView(children: [
//           Balance(),
//         ]),
//       ),
//     );
//   }
// }

// class Balance extends StatelessWidget {
//   @override
//   Widget build(BuildContext context) {
//     return Column(
//       children: [
//         Container(
//           width: 350,
//           height: 167,
//           child: Stack(
//             children: [
//               Positioned(
//                 left: 0,
//                 top: 0,
//                 child: Container(
//                   width: 350,
//                   height: 167,
//                   decoration: ShapeDecoration(
//                     color: Colors.white,
//                     shape: RoundedRectangleBorder(
//                       borderRadius: BorderRadius.circular(12),
//                     ),
//                     shadows: [
//                       BoxShadow(
//                         color: Color(0x0A000000),
//                         blurRadius: 32,
//                         offset: Offset(0, 2),
//                         spreadRadius: 0,
//                       )
//                     ],
//                   ),
//                 ),
//               ),
//               Positioned(
//                 left: 254,
//                 top: 16,
//                 child: Container(
//                   width: 80,
//                   height: 32,
//                   child: Stack(
//                     children: [
//                       Positioned(
//                         left: 0,
//                         top: 0,
//                         child: Text.rich(
//                           TextSpan(
//                             children: [
//                               TextSpan(
//                                 text: '\$ 6.1\n',
//                                 style: TextStyle(
//                                   color: Color(0xFF00F439),
//                                   fontSize: 16,
//                                   fontFamily: 'Readex Pro',
//                                   fontWeight: FontWeight.w500,
//                                   height: 0,
//                                 ),
//                               ),
//                               TextSpan(
//                                 text: 'saved Yesterday.',
//                                 style: TextStyle(
//                                   color: Color(0xFF2E2E2E),
//                                   fontSize: 10,
//                                   fontFamily: 'Readex Pro',
//                                   fontWeight: FontWeight.w400,
//                                   height: 0,
//                                 ),
//                               ),
//                             ],
//                           ),
//                           textAlign: TextAlign.right,
//                         ),
//                       ),
//                       Positioned(
//                         left: 27,
//                         top: 1,
//                         child: Container(
//                           width: 16,
//                           height: 16,
//                           child: Stack(
//                             children: [
//                               Positioned(
//                                 left: 0,
//                                 top: 0,
//                                 child: Container(
//                                   width: 16,
//                                   height: 16,
//                                   decoration: BoxDecoration(color: Color(0xFFD9D9D9)),
//                                 ),
//                               ),
//                             ],
//                           ),
//                         ),
//                       ),
//                     ],
//                   ),
//                 ),
//               ),
//               Positioned(
//                 left: 16,
//                 top: 52,
//                 child: Text(
//                   '\$ 14,489.60',
//                   style: TextStyle(
//                     color: Color(0xFF2E2E2E),
//                     fontSize: 28,
//                     fontFamily: 'Readex Pro',
//                     fontWeight: FontWeight.w600,
//                     height: 0,
//                   ),
//                 ),
//               ),
//               Positioned(
//                 left: 16,
//                 top: 16,
//                 child: Text(
//                   'Carbon Balance',
//                   style: TextStyle(
//                     color: Color(0xFF2E2E2E),
//                     fontSize: 16,
//                     fontFamily: 'Readex Pro',
//                     fontWeight: FontWeight.w500,
//                     height: 0,
//                   ),
//                 ),
//               ),
//               Positioned(
//                 left: 16,
//                 top: 111,
//                 child: Container(
//                   width: 318,
//                   height: 40,
//                   child: Stack(
//                     children: [
//                       Positioned(
//                         left: 0,
//                         top: 0,
//                         child: Container(
//                           width: 151,
//                           height: 40,
//                           padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 6),
//                           decoration: ShapeDecoration(
//                             color: Color(0xFF00F439),
//                             shape: RoundedRectangleBorder(
//                               side: BorderSide(width: 1, color: Color(0xFF00F439)),
//                               borderRadius: BorderRadius.circular(4),
//                             ),
//                           ),
//                           child: Row(
//                             mainAxisSize: MainAxisSize.min,
//                             mainAxisAlignment: MainAxisAlignment.center,
//                             crossAxisAlignment: CrossAxisAlignment.center,
//                             children: [
//                               Text(
//                                 'Add Cash',
//                                 style: TextStyle(
//                                   color: Color(0xFF2E2E2E),
//                                   fontSize: 14,
//                                   fontFamily: 'Poppins',
//                                   fontWeight: FontWeight.w600,
//                                   height: 0.10,
//                                 ),
//                               ),
//                             ],
//                           ),
//                         ),
//                       ),
//                       Positioned(
//                         left: 167,
//                         top: 0,
//                         child: Container(
//                           width: 151,
//                           height: 40,
//                           padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 6),
//                           decoration: ShapeDecoration(
//                             color: Color(0xFF2E2E2E),
//                             shape: RoundedRectangleBorder(
//                               side: BorderSide(width: 1, color: Color(0xFF2E2E2E)),
//                               borderRadius: BorderRadius.circular(4),
//                             ),
//                           ),
//                           child: Row(
//                             mainAxisSize: MainAxisSize.min,
//                             mainAxisAlignment: MainAxisAlignment.center,
//                             crossAxisAlignment: CrossAxisAlignment.center,
//                             children: [
//                               Text(
//                                 'Cash Out',
//                                 style: TextStyle(
//                                   color: Colors.white,
//                                   fontSize: 14,
//                                   fontFamily: 'Poppins',
//                                   fontWeight: FontWeight.w600,
//                                   height: 0.10,
//                                 ),
//                               ),
//                             ],
//                           ),
//                         ),
//                       ),
//                     ],
//                   ),
//                 ),
//               ),
//             ],
//           ),
//         ),
//       ],
//     );
//   }
// }

